name 'docker_host'
maintainer 'Ryan Ovrevik'
maintainer_email 'rlo+github@ovrevik.com'
license 'MIT'
description 'Installs/Configures docker_host'
long_description 'Installs/Configures docker_host'
version '0.1.0'
